dist: xenial
language: python
sudo: required

python:
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - postgresql

env:
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to install dependencies
install:
  - sudo apt-get install -y gdal-bin
  - pip install -r requirements.txt

# command to run tests
script:
  - ./manage.py test
