dist: xenial
language: python
sudo: required

python:
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - postgresql

env:
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

before_script:
  - createuser -U postgres -d mario --superuser
  - createdb -U mario ghini
  - psql ghini mario -c "create extension postgis"

# command to install dependencies
install:
  - sudo apt-get install -y gdal-bin
  - pip install -r requirements.txt

# command to run tests
script:
  - ./manage.py test
